# Programmation Oriented Object
***

In [1]:
from webspirit.tools.checktype import CheckType, ValidatePathOrUrl, StrPath, HyperLink, PathOrURL

from webspirit.tools.contexterror import ErrorContextManager as ECM

from webspirit.tools.contexterror import ecm, raise_error, re

from webspirit.tools.csvmanager import CSVManager, Music

from webspirit.tools.jsonmanager import JSONManager

In [2]:
from webspirit.config.constants import LOGGER, PATH_LANGUAGES, PATH_MUSICS_LIST

from webspirit.config.logger import CONSOLE, INFO, ERROR, WARNING, DEBUG

from webspirit.config.introspection import show

In [3]:
from webspirit.system.resources.bookmarks import Bookmarks

In [4]:
from rich import pretty, traceback

from rich.console import Console

import builtins

# pretty.install()
traceback.install(show_locals=True)

builtins.print = CONSOLE.print

In [5]:
from os.path import abspath

In [6]:
# Configuration for the logger output
LOGGER.disabled = False

# Relative path
PATH_LANGUAGES, PATH_MUSICS_LIST = StrPath(PATH_LANGUAGES).relpath(), StrPath(PATH_MUSICS_LIST).relpath()

# *contexterror.py*

## ErrorContextManager or *ecm*

In [7]:
@ECM("Error in the divide function 1") # or ecm
def divide(a: int, b: int) -> float:
    return a / b

divide(10, 0)

2025-10-02 17:32:27   interactiveshell.py:3699  WARNING  Error in the divide function 1

In [8]:
@ecm("Error in the divide function 2", error=True)
def divide(a: int, b: int) -> float:
    return a / b

divide(10, 0)

2025-10-02 17:32:27   interactiveshell.py:3699  WARNING  Error in the divide function 2
Traceback (most recent call last):
  File "C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tools\contexterror.py", line 37, in _function
    return fonction(*args, **kwargs)
  File "C:\Users\Blondel\AppData\Local\Temp\ipykernel_2388\2736032603.py", line 3, in divide
    return a / b
           ~~^~~
ZeroDivisionError: division by zero

In [9]:
with ecm("Error in the block", WARNING):
    x = 1 / 0

2025-10-02 17:32:27   interactiveshell.py:3639  WARNING  Error in the block

## raise_error or *re*

In [10]:
with ecm("Error in the example function", error=True): # let=False
    raise_error("Something wrong", error=RuntimeError) # or re

2025-10-02 17:32:27   interactiveshell.py:3639  WARNING  Error in the example function
Traceback (most recent call last):
  File "C:\Users\Blondel\AppData\Local\Temp\ipykernel_2388\926349046.py", line 2, in <module>
    raise_error("Something wrong", error=RuntimeError) # or re
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tools\contexterror.py", line 66, in raise_error
    raise error(message)
RuntimeError: Something wrong

# *checktype.py*

## HyperLink

In [11]:
HyperLink.__mro__

(webspirit.tools.checktype.HyperLink,
 str,
 webspirit.tools.checktype._PathOrURL,
 object)

### Methods

In [12]:
HyperLink.is_url('https://youtu.be/kO8Nj09525U')

True

In [13]:
HyperLink.is_url(HyperLink('https://youtu.be/kO8Nj09525U'))

True

In [14]:
HyperLink.is_url('Hello Word!')

False

### Examples

In [15]:
url = HyperLink('https://youtu.be/kO8Nj09525U')

In [16]:
show(url)

str  : https://youtu.be/kO8Nj09525U
repr : HyperLink('https://youtu.be/kO8Nj09525U')

In [17]:
with ecm():
    HyperLink('https://')

In [18]:
id(url) == id(url.copy())

False

## StrPath

In [19]:
StrPath.__mro__

(webspirit.tools.checktype.StrPath,
 pathlib._local.Path,
 pathlib._abc.PathBase,
 pathlib._local.PurePath,
 pathlib._abc.PurePathBase,
 webspirit.tools.checktype._PathOrURL,
 object)

### Methods

In [20]:
PATH_LANGUAGES

StrPath('..\data\languages.csv')

In [21]:
StrPath.is_path(r"C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\data\languages.csv")

True

In [22]:
StrPath.is_path(str(PATH_LANGUAGES))

True

In [23]:
StrPath.is_path(StrPath(PATH_LANGUAGES))

True

In [24]:
StrPath.is_path(abspath(r'..\data\musics.csv'), suffix=('csv', 'txt'))

True

In [25]:
StrPath.is_path(abspath(r'..\data\musics.csv'), suffix='csv')

True

In [26]:
StrPath.is_path(abspath(r'..\data'), dir=True)

True

In [27]:
PATH_LANGUAGES.copy().absolute(), PATH_LANGUAGES.copy().relpath(), PATH_LANGUAGES.copy().dirname()

(StrPath('c:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\notebooks\..\data\languages.csv'),
 StrPath('..\data\languages.csv'),
 StrPath('..\data'))

### Examples

In [28]:
path = StrPath(PATH_LANGUAGES)

In [29]:
show(path)

str  : ..\data\languages.csv
repr : StrPath('..\data\languages.csv')

In [30]:
with ecm():
    StrPath(r'..\src\data\musics.cpp')

In [31]:
id(path) == id(path.copy())

False

## CheckType & ValidatePathOrUrl

In [32]:
class BookOfLink:
    @CheckType
    def append_url1(self, url: HyperLink, nbr: int) -> tuple[HyperLink, int]:
        return type(url), type(nbr)

    @CheckType
    def append_url2(self, url: str, nbr: int | None = None) -> tuple[str, int | None]:
        return type(url), type(nbr)

    @CheckType
    def append_url3(self, url: HyperLink, nbr: int, string: str) -> tuple[HyperLink, int, str]:
        return type(url), type(nbr), type(string)

    @CheckType('path')
    def append_path(self, path: StrPath) -> StrPath:
        return type(path)

    @ValidatePathOrUrl('link')
    def append1(self, link: PathOrURL = "https://youtu.be/_0Pf48RqSsg") -> PathOrURL:
        return type(link)

    @ValidatePathOrUrl('url')
    def append2(self, url: HyperLink) -> HyperLink:
        return type(url)

In [33]:
BookOfLink.append1.__qualname__
BookOfLink.append1.__code__

In [34]:
@CheckType
def append_url1(url: HyperLink, nbr: int) -> tuple[HyperLink, int]:
    return type(url), type(nbr)

@CheckType
def append_url2(url: str, nbr: int | None = None) -> tuple[str, int | None]:
    return type(url), type(nbr)

@CheckType('url', 'nbr', 'string')
def append_url3(url: HyperLink, nbr: int, string: str) -> tuple[HyperLink, int, str]:
    return type(url), type(nbr), type(string)

@CheckType('path')
def append_path(path: StrPath) -> StrPath:
    return type(path)

@ValidatePathOrUrl('link')
def append1(link: PathOrURL = "https://youtu.be/_0Pf48RqSsg") -> PathOrURL:
    return type(link)

@ValidatePathOrUrl('url')
def append2(url: HyperLink) -> HyperLink:
    return type(url)

### CheckType

#### Simple Example

In [35]:
@CheckType(return_=True)
def function_1(arg1: str, arg2: str) -> int:
    return arg1 + arg2

function_1('1', 0)

2025-10-02 17:32:28                In[35]:5     DEBUG    Change the parameter arg2 of function_1 with a '0' value and a type <class 'int'> to type <class 'str'>
2025-10-02 17:32:28   interactiveshell.py:3699  DEBUG    Change the parameter return of function_1 with a '10' value and a type <class 'str'> to type <class 'int'>

10

In [36]:
@CheckType('arg2', return_=True)
def function_2(arg1, arg2: str) -> int:
    return arg1 + arg2

function_2('1', 0)

2025-10-02 17:32:28                In[36]:5     DEBUG    Change the parameter arg2 of function_2 with a '0' value and a type <class 'int'> to type <class 'str'>
2025-10-02 17:32:28   interactiveshell.py:3699  DEBUG    Change the parameter return of function_2 with a '10' value and a type <class 'str'> to type <class 'int'>

10

In [37]:
@CheckType(convert=False)
def function_3(arg1: str, arg2: str) -> int:
    return arg1 + arg2

with ecm('An error was occurred in the function_3'):
    function_3('1', 0)

2025-10-02 17:32:28   interactiveshell.py:3639  WARNING  An error was occurred in the function_3

In [38]:
@CheckType('arg1', 'a')
def function_4(arg1: str, arg2: str) -> int:
    return arg1 + arg2

with ecm('An error was occurred in the function_4'):
    function_4('1', '0')

2025-10-02 17:32:29   interactiveshell.py:3639  WARNING  An error was occurred in the function_4

In [39]:
@CheckType
def function_5(arg1: str, arg2: str) -> str:
    return arg1 + arg2

function_5('1', 0)

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter arg2 of function_5 with a '0' value and a type <class 'int'> to type <class 'str'>

'10'

#### Big Example

##### Class

In [40]:
book = BookOfLink()

In [41]:
book.append_url1('https://youtu.be/1V_xRb0x9aw', 7)

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter url of append_url1 with a 'https://youtu.be/1V_xRb0x9aw' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

(webspirit.tools.checktype.HyperLink, int)

In [42]:
book.append_url2('https://youtu.be/1V_xRb0x9aw', '7')

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter nbr of append_url2 with a '7' value and a type <class 'str'> to type <class 'int'>

(str, int)

In [43]:
book.append_url2('https://youtu.be/1V_xRb0x9aw')

(str, NoneType)

In [44]:
book.append_url3('https://youtu.be/1V_xRb0x9aw', '7', 190)

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter url of append_url3 with a 'https://youtu.be/1V_xRb0x9aw' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>
2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter nbr of append_url3 with a '7' value and a type <class 'str'> to type <class 'int'>
2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter string of append_url3 with a '190' value and a type <class 'int'> to type <class 'str'>

(webspirit.tools.checktype.HyperLink, int, str)

In [45]:
book.append_path(str(PATH_MUSICS_LIST))

2025-10-02 17:32:29                In[45]:1     DEBUG    Change the parameter path of append_path with a '..\data\musics.csv' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [46]:
with ecm():
    book.append_path("data/musics.txt")

##### Function

In [47]:
append_url1('https://youtu.be/1V_xRb0x9aw', 7)

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter url of append_url1 with a 'https://youtu.be/1V_xRb0x9aw' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

(webspirit.tools.checktype.HyperLink, int)

In [48]:
append_url2('https://youtu.be/1V_xRb0x9aw', '7')

2025-10-02 17:32:29          checktype.py:213   DEBUG    Change the parameter nbr of append_url2 with a '7' value and a type <class 'str'> to type <class 'int'>

(str, int)

In [49]:
append_url2('https://youtu.be/1V_xRb0x9aw')

(str, NoneType)

In [50]:
append_url3('https://youtu.be/1V_xRb0x9aw', '7', 190)

2025-10-02 17:32:29                In[50]:1     DEBUG    Change the parameter url of append_url3 with a 'https://youtu.be/1V_xRb0x9aw' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>
2025-10-02 17:32:29                In[50]:1     DEBUG    Change the parameter nbr of append_url3 with a '7' value and a type <class 'str'> to type <class 'int'>
2025-10-02 17:32:29                In[50]:1     DEBUG    Change the parameter string of append_url3 with a '190' value and a type <class 'int'> to type <class 'str'>

(webspirit.tools.checktype.HyperLink, int, str)

In [51]:
append_path(str(PATH_MUSICS_LIST))

2025-10-02 17:32:29                In[51]:1     DEBUG    Change the parameter path of append_path with a '..\data\musics.csv' value and a type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [52]:
with ecm():
    append_path("data/musics.txt")

### ValidatePathOrUrl

#### Class

In [53]:
book.append1(str(PATH_MUSICS_LIST))

2025-10-02 17:32:29                In[53]:1     DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [54]:
book.append2("https://youtu.be/1V_xRb0x9aw")

2025-10-02 17:32:29                In[54]:1     DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

webspirit.tools.checktype.HyperLink

#### Function

In [55]:
append1(str(PATH_MUSICS_LIST))

2025-10-02 17:32:29                In[55]:1     DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [56]:
append2("https://youtu.be/1V_xRb0x9aw")

2025-10-02 17:32:29                In[56]:1     DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

webspirit.tools.checktype.HyperLink

# *jsonmanager.py*

In [57]:
path = StrPath('c:/home/blondel/files/test.py', exist=False)

path.name, path.stem, path.suffix

2025-10-02 17:32:30   interactiveshell.py:3639  DEBUG    Skip existing test for 'c:/home/blondel/files/test.py'
C:\Users\Blondel\AppData\Local\Temp\ipykernel_2388\3300180144.py:1: DeprecationWarning: support for supplying keyword arguments to pathlib.PurePath is deprecated and scheduled for removal in Python 3.14
  path = StrPath('c:/home/blondel/files/test.py', exist=False)

('test.py', 'test', '.py')

In [58]:
bookmarks = Bookmarks()
bookmarks.path

2025-10-02 17:32:30                In[58]:1     DEBUG    Skip existing test for 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\Bookmarks.json'

StrPath('C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\Bookmarks.json')

In [59]:
bookmarks.get_bookmarks

In [60]:
json = JSONManager(bookmarks.path)

2025-10-02 17:32:30   interactiveshell.py:3699  WARNING  load function hasn't parameters
2025-10-02 17:32:30          checktype.py:188   DEBUG    Skip existing test for '..\tmp\Bookmarks.json'
2025-10-02 17:32:30          checktype.py:188   DEBUG    Skip existing test for 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp'
2025-10-02 17:32:30        jsonmanager.py:14    INFO     Load 'Bookmarks.json' in 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp'

# *csvmanager.py*

## Music

In [61]:
Music.__mro__

(webspirit.tools.csvmanager.Music, object)

In [62]:
music = Music('https://youtu.be/kO8Nj09525U')

2025-10-02 17:32:30                In[62]:1     DEBUG    Change 'https://youtu.be/kO8Nj09525U' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

In [63]:
show(music)

str  : https://youtu.be/kO8Nj09525U
repr : Music(youtube_url=HyperLink('https://youtu.be/kO8Nj09525U'), path=None, extension=None, type=None,
spotify_url=None, picture=None, meta=None)

In [64]:
youtube_url, path, extension, type, spotify_url, picture, meta = music

In [65]:
youtube_url, path, extension, type, spotify_url, picture, meta

(HyperLink('https://youtu.be/kO8Nj09525U'), None, None, None, None, None, None)

## CSVManager

### Methods

In [66]:
csv = CSVManager(PATH_LANGUAGES, headers=None)

2025-10-02 17:32:30   interactiveshell.py:3699  INFO     Load 'languages.csv' in '..\data'
2025-10-02 17:32:30          checktype.py:167   INFO     Save the DataFrame in '..\data\languages.csv'

In [67]:
csv.path.relpath()

StrPath('..\data\languages.csv')

In [68]:
csv.length, csv.width

(2, 157)

In [69]:
csv.size

(2, 157)

In [70]:
csv

CSVManager(path=..\data\languages.csv, length=2, width=157)

### Examples

In [71]:
csv = CSVManager()

2025-10-02 17:32:30                In[71]:1     INFO     Create C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\tmp_musics.csv, because doesn't exist
2025-10-02 17:32:30                In[71]:1     DEBUG    Change 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\tmp_musics.csv' of type <class 'pathlib._local.WindowsPath'> to type <class 'webspirit.tools.checktype.StrPath'>
2025-10-02 17:32:30   interactiveshell.py:3699  INFO     Load 'tmp_musics.csv' in 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp'
2025-10-02 17:32:30          checktype.py:167   INFO     Save the DataFrame in '..\tmp\tmp_musics.csv'

In [72]:
repr(csv)

'CSVManager(path=..\\tmp\\tmp_musics.csv, length=7, width=0)'

In [73]:
csv.append(PATH_MUSICS_LIST)

2025-10-02 17:32:30   interactiveshell.py:3699  INFO     Load '..\data\musics.csv' in '..\data'
2025-10-02 17:32:30          checktype.py:167   INFO     Save the DataFrame in '..\tmp\tmp_musics.csv'

In [74]:
repr(csv)

'CSVManager(path=..\\tmp\\tmp_musics.csv, length=7, width=25)'

In [75]:
csv

CSVManager(path=..\tmp\tmp_musics.csv, length=7, width=25)

In [76]:
with ecm():
    csv.append(r"C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\YouTubeDownloader\src\ytload\data\musics_copy.csv")

In [77]:
csv.size

(7, 25)

In [78]:
with ecm():
    csv.append('https://youtu.be/-xmuUbw5vyc')

In [79]:
csv.delete()