# Programmation Oriented Object
***

In [1]:
from webspirit.tools.checktype import CheckType, ValidatePathOrUrl, StrPath, HyperLink, PathOrURL

from webspirit.tools.contexterror import ErrorContextManager as ECM

from webspirit.tools.contexterror import ecm, raise_error, re

from webspirit.tools.introspection import show, exception

from webspirit.tools.csvmanager import CSVManager, Music

from webspirit.tools.jsonmanager import JSONManager

In [2]:
from webspirit.config.constants import LOGGER, PATH_LANGUAGES, PATH_MUSICS_LIST

from webspirit.config.logger import INFO, ERROR, WARNING, DEBUG

In [3]:
from os.path import abspath

In [4]:
# Configuration for the logger output
LOGGER.disabled = False

# Relative path
PATH_LANGUAGES, PATH_MUSICS_LIST = StrPath(PATH_LANGUAGES).relpath(), StrPath(PATH_MUSICS_LIST).relpath()

# *contexterror.py*

## ErrorContextManager or *ecm*

In [5]:
@ECM("Error in the divide function 1") # or ecm
def divide(a: int, b: int) -> float:
    return a / b

divide(10, 0)

2025-08-30 15:35:49  webspirit.config.logger  WARNING  Error in the divide function 1

In [6]:
@ecm("Error in the divide function 2", error=True)
def divide(a: int, b: int) -> float:
    return a / b

divide(10, 0)

2025-08-30 15:35:49  webspirit.config.logger  WARNING  Error in the divide function 2
Traceback (most recent call last):
  File "C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tools\contexterror.py", line 28, in _function
    return fonction(*args, **kwargs)
  File "C:\Users\Blondel\AppData\Local\Temp\ipykernel_13412\2736032603.py", line 3, in divide
    return a / b
           ~~^~~
ZeroDivisionError: division by zero

In [7]:
with ecm("Error in the block", WARNING):
    x = 1 / 0

2025-08-30 15:35:49  webspirit.config.logger  WARNING  Error in the block

## raise_error or *re*

In [8]:
with ecm("Error in the example function", error=True): # let=False
    raise_error("Something wrong", error=RuntimeError) # or re

2025-08-30 15:35:49  webspirit.config.logger  ERROR    Something wrong
2025-08-30 15:35:49  webspirit.config.logger  WARNING  Error in the example function
Traceback (most recent call last):
  File "C:\Users\Blondel\AppData\Local\Temp\ipykernel_13412\926349046.py", line 2, in <module>
    raise_error("Something wrong", error=RuntimeError) # or re
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tools\contexterror.py", line 55, in raise_error
    raise error(message)
RuntimeError: Something wrong

# *checktype.py*

## HyperLink

In [9]:
HyperLink.__mro__

(webspirit.tools.checktype.HyperLink,
 str,
 webspirit.tools.checktype._PathOrURL,
 object)

### Methods

In [10]:
HyperLink.is_url('https://youtu.be/kO8Nj09525U')

True

In [11]:
HyperLink.is_url(HyperLink('https://youtu.be/kO8Nj09525U'))

True

In [12]:
HyperLink.is_url('Hello Word!')

False

### Examples

In [13]:
url = HyperLink('https://youtu.be/kO8Nj09525U')

In [14]:
show(url)

str  : https://youtu.be/kO8Nj09525U
repr : HyperLink('https://youtu.be/kO8Nj09525U')

In [15]:
exception(HyperLink, string='https://')

2025-08-30 15:35:49  webspirit.config.logger  ERROR    'https://' must be a valid hyperlink

TypeError("'https://' must be a valid hyperlink")

In [16]:
id(url) == id(url.copy())

False

## StrPath

In [17]:
StrPath.__mro__

(webspirit.tools.checktype.StrPath,
 pathlib._local.Path,
 pathlib._abc.PathBase,
 pathlib._local.PurePath,
 pathlib._abc.PurePathBase,
 webspirit.tools.checktype._PathOrURL,
 object)

### Methods

In [18]:
PATH_LANGUAGES

StrPath('..\data\languages.csv')

In [66]:
StrPath.is_path(r"C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\data\languages.csv")

True

In [20]:
StrPath.is_path(str(PATH_LANGUAGES))

True

In [21]:
StrPath.is_path(StrPath(PATH_LANGUAGES))

True

In [22]:
StrPath.is_path(abspath(r'..\data\musics.csv'), suffix=('csv', 'txt'))

True

In [23]:
StrPath.is_path(abspath(r'..\data\musics.csv'), suffix='csv')

True

In [24]:
StrPath.is_path(abspath(r'..\data'), dir=True)

True

In [25]:
PATH_LANGUAGES.copy().absolute(), PATH_LANGUAGES.copy().relpath(), PATH_LANGUAGES.copy().dirname()

(StrPath('..\data\languages.csv'),
 StrPath('..\data\languages.csv'),
 StrPath('..\data'))

### Examples

In [26]:
path = StrPath(PATH_LANGUAGES)

In [27]:
show(path)

str  : ..\data\languages.csv
repr : StrPath('..\data\languages.csv')

In [28]:
exception(StrPath, string=r'..\src\data\musics.cpp')

2025-08-30 15:35:50  webspirit.config.logger  ERROR    '..\src\data\musics.cpp' must be a valid path to a file or a directory

TypeError("'..\\src\\data\\musics.cpp' must be a valid path to a file or a directory")

In [29]:
id(path) == id(path.copy())

False

## CheckType & ValidatePathOrUrl

In [30]:
class BookOfLink:
    @CheckType()
    def append_url1(self, url: HyperLink, nbr: int) -> tuple[HyperLink, int]:
        return type(url), type(nbr)

    @CheckType()
    def append_url2(self, url: str, nbr: int | None = None) -> tuple[str, int | None]:
        return type(url), type(nbr)

    @CheckType('url', 'nbr', 'string')
    def append_url3(self, url: HyperLink, nbr: int, string: str) -> tuple[HyperLink, int, str]:
        return type(url), type(nbr), type(string)

    @CheckType('path')
    def append_path(self, path: StrPath) -> StrPath:
        return type(path)

    @ValidatePathOrUrl('link')
    def append1(self, link: PathOrURL = "https://youtu.be/_0Pf48RqSsg") -> PathOrURL:
        return type(link)

    @ValidatePathOrUrl('url')
    def append2(self, url: HyperLink) -> HyperLink:
        return type(url)

In [31]:
@CheckType()
def append_url1(url: HyperLink, nbr: int) -> tuple[HyperLink, int]:
    return type(url), type(nbr)

@CheckType()
def append_url2(url: str, nbr: int | None = None) -> tuple[str, int | None]:
    return type(url), type(nbr)

@CheckType('url', 'nbr', 'string')
def append_url3(url: HyperLink, nbr: int, string: str) -> tuple[HyperLink, int, str]:
    return type(url), type(nbr), type(string)

@CheckType('path')
def append_path(path: StrPath) -> StrPath:
    return type(path)

@ValidatePathOrUrl('link')
def append1(link: PathOrURL = "https://youtu.be/_0Pf48RqSsg") -> PathOrURL:
    return type(link)

@ValidatePathOrUrl('url')
def append2(url: HyperLink) -> HyperLink:
    return type(url)

### CheckType

#### Class

In [32]:
book = BookOfLink()

In [33]:
book.append_url1('https://youtu.be/1V_xRb0x9aw', 7)

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

(webspirit.tools.checktype.HyperLink, int)

In [34]:
book.append_url2('https://youtu.be/1V_xRb0x9aw', '7')

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '7' of type <class 'str'> to type <class 'int'>

(str, int)

In [35]:
book.append_url2('https://youtu.be/1V_xRb0x9aw')

(str, NoneType)

In [36]:
book.append_url3('https://youtu.be/1V_xRb0x9aw', '7', 190)

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>
2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '7' of type <class 'str'> to type <class 'int'>
2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '190' of type <class 'int'> to type <class 'str'>

(webspirit.tools.checktype.HyperLink, int, str)

In [37]:
book.append_path(str(PATH_MUSICS_LIST))

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [38]:
exception(book.append_path, "data/musics.txt")

2025-08-30 15:35:50  webspirit.config.logger  ERROR    'data/musics.txt' must be a valid path to a file or a directory
2025-08-30 15:35:50  webspirit.config.logger  ERROR    'path' object with 'data/musics.txt' value, can't be converted to <class 'webspirit.tools.checktype.StrPath'>

ValueError("'path' object with 'data/musics.txt' value, can't be converted to <class 'webspirit.tools.checktype.StrPath'>")

#### Function

In [39]:
append_url1('https://youtu.be/1V_xRb0x9aw', 7)

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

(webspirit.tools.checktype.HyperLink, int)

In [40]:
append_url2('https://youtu.be/1V_xRb0x9aw', '7')

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '7' of type <class 'str'> to type <class 'int'>

(str, int)

In [41]:
append_url2('https://youtu.be/1V_xRb0x9aw')

(str, NoneType)

In [42]:
append_url3('https://youtu.be/1V_xRb0x9aw', '7', 190)

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>
2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '7' of type <class 'str'> to type <class 'int'>
2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '190' of type <class 'int'> to type <class 'str'>

(webspirit.tools.checktype.HyperLink, int, str)

In [43]:
append_path(str(PATH_MUSICS_LIST))

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [44]:
exception(append_path, "data/musics.txt")

2025-08-30 15:35:50  webspirit.config.logger  ERROR    'data/musics.txt' must be a valid path to a file or a directory
2025-08-30 15:35:50  webspirit.config.logger  ERROR    'path' object with 'data/musics.txt' value, can't be converted to <class 'webspirit.tools.checktype.StrPath'>

ValueError("'path' object with 'data/musics.txt' value, can't be converted to <class 'webspirit.tools.checktype.StrPath'>")

### ValidatePathOrUrl

#### Class

In [45]:
book.append1(str(PATH_MUSICS_LIST))

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [46]:
book.append2("https://youtu.be/1V_xRb0x9aw")

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

webspirit.tools.checktype.HyperLink

#### Function

In [47]:
append1(str(PATH_MUSICS_LIST))

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change '..\data\musics.csv' of type <class 'str'> to type <class 'webspirit.tools.checktype.StrPath'>

webspirit.tools.checktype.StrPath

In [48]:
append2("https://youtu.be/1V_xRb0x9aw")

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/1V_xRb0x9aw' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

webspirit.tools.checktype.HyperLink

# *jsonmanager.py*

In [49]:
#JSONManager.load()

# *csvmanager.py*

## Music

In [50]:
Music.__mro__

(webspirit.tools.csvmanager.Music, object)

In [51]:
music = Music('https://youtu.be/kO8Nj09525U')

2025-08-30 15:35:50  webspirit.config.logger  DEBUG    Change 'https://youtu.be/kO8Nj09525U' of type <class 'str'> to type <class 'webspirit.tools.checktype.HyperLink'>

In [52]:
show(music)

str  : https://youtu.be/kO8Nj09525U
repr : Music(youtube_url=HyperLink('https://youtu.be/kO8Nj09525U'), path=None, extension=None, type=None, spotify_url=None, picture=None, meta=None)

In [53]:
youtube_url, path, extension, type, spotify_url, picture, meta = music

In [54]:
youtube_url, path, extension, type, spotify_url, picture, meta

(HyperLink('https://youtu.be/kO8Nj09525U'), None, None, None, None, None, None)

## CSVManager

### Methods

In [55]:
csv = CSVManager(PATH_LANGUAGES, headers=None)

2025-08-30 15:35:50  webspirit.config.logger  INFO     Load 'languages.csv' in '..\data'
2025-08-30 15:35:50  webspirit.config.logger  INFO     Save the DataFrame in '..\data\languages.csv'

In [56]:
csv.path.relpath()

StrPath('..\data\languages.csv')

In [57]:
csv.length, csv.width

(2, 157)

In [58]:
csv.size

(2, 157)

In [59]:
csv

CSVManager(path=..\data\languages.csv, length=2, width=157)

### Examples

In [60]:
csv = CSVManager()

2025-08-30 15:35:51  webspirit.config.logger  DEBUG    Create C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\tmp_musics.csv, because doesn't exist
2025-08-30 15:35:51  webspirit.config.logger  DEBUG    Change 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\Webspirit\src\webspirit\tmp\tmp_musics.csv' of type <class 'pathlib._local.WindowsPath'> to type <class 'webspirit.tools.checktype.StrPath'>
2025-08-30 15:35:51  webspirit.config.logger  INFO     Load 'tmp_musics.csv' in '..\tmp'
2025-08-30 15:35:51  webspirit.config.logger  INFO     Save the DataFrame in '..\tmp\tmp_musics.csv'

In [61]:
repr(csv)

'CSVManager(path=..\\tmp\\tmp_musics.csv, length=7, width=0)'

In [62]:
csv.append(PATH_MUSICS_LIST)

2025-08-30 15:35:51  webspirit.config.logger  INFO     Load '..\data\musics.csv' in '..\data'
2025-08-30 15:35:51  webspirit.config.logger  INFO     Save the DataFrame in '..\tmp\tmp_musics.csv'

In [63]:
repr(csv)

'CSVManager(path=..\\tmp\\tmp_musics.csv, length=7, width=25)'

In [64]:
csv

CSVManager(path=..\tmp\tmp_musics.csv, length=7, width=25)

In [65]:
csv.append(r"C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\YouTubeDownloader\src\ytload\data\musics_copy.csv")

2025-08-30 15:35:51  webspirit.config.logger  ERROR    'resource' object with 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\YouTubeDownloader\src\ytload\data\musics_copy.csv' must be a valid url or a path to a csv or a txt file

ValueError: 'resource' object with 'C:\Users\Blondel\Documents\Programmation\Langage\Python\Projects\PyForge\plugins\YouTubeDownloader\src\ytload\data\musics_copy.csv' must be a valid url or a path to a csv or a txt file

In [ ]:
csv.size

In [ ]:
exception(csv.append, 'https://youtu.be/-xmuUbw5vyc')

In [ ]:
csv.delete()